name: CountdownWidget
options:
  bundleIdPrefix: com.shawjj
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    SWIFT_VERSION: "5.9"

targets:
  CountdownWidget:
    type: application
    platform: iOS
    sources:
      - path: CountdownWidget
      - path: Shared
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait"
        PRODUCT_BUNDLE_IDENTIFIER: com.shawjj.countdownwidget
        CODE_SIGN_ENTITLEMENTS: CountdownWidget/CountdownWidget.entitlements
    entitlements:
      path: CountdownWidget/CountdownWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.shawjj.countdownwidget
    dependencies:
      - target: CountdownWidgetExtension

  CountdownWidgetExtension:
    type: app-extension
    platform: iOS
    product: CountdownWidgetExtension
    sources:
      - path: CountdownWidgetExtension
      - path: Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shawjj.countdownwidget.widget
        CODE_SIGN_ENTITLEMENTS: CountdownWidgetExtension/CountdownWidgetExtension.entitlements
        INFOPLIST_KEY_CFBundleDisplayName: CountdownWidget
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
    entitlements:
      path: CountdownWidgetExtension/CountdownWidgetExtension.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.shawjj.countdownwidget
